# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=3)),
                ('wage', models.FloatField()),
            ],
        ),
    ]
