# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160304_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundvolumedata',
            old_name='tt_total_net_assets_under_management',
            new_name='total_net_assets_under_management',
        ),
    ]
