# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160304_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_scheme',
        ),
        migrations.DeleteModel(
            name='FundScheme',
        ),
    ]
