# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160304_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='symbol',
            field=models.CharField(max_length=15),
        ),
    ]
